GOOGLE_CATEGORIES = [
    ['accent chairs', 'furniture > chairs > arm chairs, recliners & sleeper chairs'],
    ['beddings', 'home & garden > linens & bedding > bedding'],
    ['bedroom sets', 'furniture > furniture sets > bedroom furniture sets'],
    ['beds', 'furniture > beds & accessories > beds & bed frames'],
    ['benches', 'furniture > benches > kitchen & dining benches'],
    ['bookcases', 'furniture > shelving > bookcases & standing shelves'],
    ['box springs', 'furniture > beds & accessories > mattress foundations'],
    ['bridges', ''],
    ['buffets', 'furniture > cabinets & storage > buffets & sideboards'],
    ['cabinets', 'furniture > cabinets & storage > buffets & sideboards'],
    ['chaises', 'furniture > chairs > chaises'],
    ['chests', 'furniture > cabinets & storage > storage chests'],
    ['chinas', 'furniture > cabinets & storage > china cabinets & hutches'],
    ['coffee table sets', 'furniture > tables > accent tables > coffee tables'],
    ['coffee tables', 'furniture > tables > accent tables > coffee tables'],
    ['console tables', 'furniture > tables > accent tables > sofa tables'],
    ['credenzas', 'furniture > cabinets & storage > china cabinets & hutches'],
    ['daybeds', 'furniture > beds & accessories > beds & bed frames'],
    ['desk chairs', 'furniture > office furniture > office chairs'],
    ['desk hutchs', 'furniture > office furniture accessories > desk parts & accessories'],
    ['desk lamps', 'furniture > office furniture accessories > desk parts & accessories'],
    ['desks', 'furniture > office furniture > desk'],
    ['dining sets', 'furniture > furniture sets > kitchen & dining furniture sets'],
    ['dining tables', 'furniture > tables > kitchen & dining room tables'],
    ['dressers', 'furniture > cabinets & storage > dressers'],
    ['end tables', 'furniture > tables > accent tables > end tables'],
    ['fireplace inserts', 'home & garden > fireplaces'],
    ['floor lamps', 'home & garden > lighting > lamps'],
    ['hutches', ''],
    ['mantels', ''],
    ['mattresses', 'furniture > bed & accessories > mattresses'],
    ['media chests', 'furniture > cabinets & storage > media storage cabinets & racks'],
    ['mirrors', 'home & garden > decor > mirrors'],
    ['nightstands', 'furniture > tables > nightstands'],
    ['office cabinets', 'furniture > cabinets & storage > file cabinets'],
    ['ottomans', 'furniture > ottomans'],
    ['pendants', 'home & garden > lighting > lamps'],
    ['piers', ''],
    ['protection plans', ''],
    ['recliners', 'furniture > chairs > arm chairs, recliners & sleeper chairs'],
    ['rugs', 'home & garden > decor > rugs'],
    ['sectional pieces', 'furniture > sofa accessories > sectional sofa units'],
    ['servers', 'furniture > cabinets & storage > buffets & sideboards'],
    ['side chairs', 'furniture > chairs > kitchen & dining room chairs'],
    ['sofa & loveseat', 'furniture > furniture sets > living room furniture sets'],
    ['sofa chairs', 'furniture > chairs > arm chairs, recliners & sleeper chairs'],
    ['sofa chaises', 'furniture > chairs > chaises'],
    ['sofas', 'furniture > sofas'],
    ['stools', 'furniture > chairs > table & bar stools'],
    ['table lamps', 'home & garden > lighting > lamps'],
    ['throw pillows', 'home & garden > decor > throw pillows'],
    ['tv stands', 'furniture > entertainment centers & tv stands'],
    ['wall arts', 'home & garden > decor > artwork > posters, prints & visual artwork'],
    ['wall units', 'furniture > shelving > wall shelves & ledges'],
]
