# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hello.Vendor'),
            preserve_default=False,
        ),
    ]
