# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorproduct',
            name='description',
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
