# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160314_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='upc',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_products',
            field=models.ManyToManyField(blank=True, null=True, to='hello.VendorProduct'),
        ),
    ]
