# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160403_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='google_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
