# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20160212_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', jsonfield.fields.JSONField(blank=True, null=True)),
                ('prices', jsonfield.fields.JSONField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
